color: null
fieldLayouts:
  f59965dd-0b70-4ece-a036-bcbc940bc902:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ce2e41ae-4673-4349-827f-0f83def33384
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3cd2dfde-db8c-48bc-9703-3e4e69aa896d
        userCondition: null
handle: cart
hasTitleField: true
icon: ''
name: cart
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
