color: null
fieldLayouts:
  0988085f-21bf-40f5-b8ec-342ce66f2517:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d45202fb-2346-4a27-8f1a-f06c6751dffb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 94059e30-1fe7-4933-84c8-af82b4d33f14
        userCondition: null
handle: footer
hasTitleField: true
icon: ''
name: footer
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
