color: null
fieldLayouts:
  19400470-a297-4adb-9f5d-a98cc584d3d2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5b0338dd-85c1-4033-bac0-aedcac0c5fe9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 622e986c-4445-4ef3-a435-a62f8438ee6e
        userCondition: null
handle: homepage
hasTitleField: true
icon: ''
name: Homepage
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
