color: null
fieldLayouts:
  a80af962-c375-4d9d-909b-e12017d084c1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 57bacb37-54a1-4cde-bc60-c7b204051785
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5e039ce8-e516-41a3-a101-9ad16712577d
        userCondition: null
handle: navigation
hasTitleField: true
icon: ''
name: navigation
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
